import subprocess
import warnings
import logging
import docopt
warnings.simplefilter(action='ignore')
warnings.filterwarnings('ignore')
logging.getLogger().setLevel(logging.CRITICAL)

print("\n")
print("#########################################################################################")
print("Multilingual Evaluation using the CARB Evaluation Strategy")
print("#########################################################################################")
print("#############")
print("English")
print("#############")
print("UD2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--tabbed=carb/english_predictions_29.tsv","--out=carb/output/lino-oie.dat"])
print("OpenIE6")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--allennlp=carb/openie6.carb","--out=carb/output/oie6.dat"])
print("IMOJIE")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--allennlp=carb/imojie.tsv","--out=carb/output/imojie.dat"])
print("OpenIE5")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--openiefive=carb/openie5_output.txt","--out=carb/output/oie5.dat"])
print("OpenIE4")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--openiefour=carb/openie4_output.txt","--binary","--out=carb/output/oie4.dat"])
print("ClausIE")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--clausie=carb/clausie_output.txt","--out=carb/output/clausie.dat"])
print("Multi2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--tabbed=carb/MultiOIE_english.txt","--out=carb/output/lino-oie.dat"])
print("PredPatt")
subprocess.call(["python","carb/carb.py","--gold=carb/extractions.tsv","--tabbed=carb/predpatt_english.tsv","--out=carb/output/lino-oie.dat"])
print("\n")
print("#############")
print("French")
print("#############")
print("UD2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/french_carb.tsv","--tabbed=carb/french_predictions_29.tsv","--out=carb/output/lino-oie.dat"])
print("Multi2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/french_carb.tsv","--tabbed=carb/MultiOIE_french.txt","--out=carb/output/lino-oie.dat"])
print("PredPatt")
subprocess.call(["python","carb/carb.py","--gold=carb/french_carb.tsv","--tabbed=carb/predpatt_french.tsv","--out=carb/output/lino-oie.dat"])
print("\n")
print("#############")
print("French Wikipedia")
print("#############")
print("Multi2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/wikipedia_fr_carb.tsv","--tabbed=carb/MultiOIE_wiki.txt","--out=carb/output/lino-oie.dat"])
print("PredPatt")
subprocess.call(["python","carb/carb.py","--gold=carb/wikipedia_fr_carb.tsv","--tabbed=carb/predpatt_french_wiki.tsv","--out=carb/output/lino-oie.dat"])
print("\n")
print("#############")
print("Spanish")
print("#############")
print("UD2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/spanish_carb.tsv","--tabbed=carb/spanish_predictions_29.tsv","--out=carb/output/lino-oie.dat"])
print("Multi2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/spanish_carb.tsv","--tabbed=carb/MultiOIE_spanish.txt","--out=carb/output/lino-oie.dat"])
print("PredPatt")
subprocess.call(["python","carb/carb.py","--gold=carb/spanish_carb.tsv","--tabbed=carb/predpatt_spanish.tsv","--out=carb/output/lino-oie.dat"])
print("\n")
print("#############")
print("Portuguese")
print("#############")
print("UD2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/portuguese_carb.tsv","--tabbed=carb/portuguese_predictions_29.tsv","--out=carb/output/lino-oie.dat"])
print("Multi2OIE")
subprocess.call(["python","carb/carb.py","--gold=carb/portuguese_carb.tsv","--tabbed=carb/MultiOIE_portuguese.txt","--out=carb/output/lino-oie.dat"])
print("PredPatt")
subprocess.call(["python","carb/carb.py","--gold=carb/portuguese_carb.tsv","--tabbed=carb/predpatt_portuguese.tsv","--out=carb/output/lino-oie.dat"])